import { Candidate } from './types'

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    fullName: 'Ana Oliveira',
    email: 'ana.oliveira@email.com',
    phone: '+55 11 99999-1111',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/anaoliveira',
    portfolio: 'anaoliveira.dev',
    desiredRole: 'Frontend Developer',
    areaOfExpertise: 'Web Development',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 8.000 – R$ 10.000',
    availabilityDate: '2026-07-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'USP',
    certifications: ['AWS Cloud Practitioner'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Senior frontend developer with 5 years building React applications for fintech companies.',
    keyTechnicalSkills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    softwareTools: ['VS Code', 'Figma', 'GitHub'],
    mainAchievements: 'Led migration of legacy jQuery app to React, reducing load time by 40%.',
    resumeFileName: 'ana-oliveira-resume.pdf',
    submittedAt: '2026-06-18T10:23:00Z',
    lastUpdatedAt: '2026-06-18T10:23:00Z',
    status: 'Under Review',
    internalNotes: 'Strong portfolio. Schedule technical interview.',
  },
  {
    id: '2',
    fullName: 'Carlos Mendes',
    email: 'carlos.mendes@email.com',
    phone: '+55 21 98888-2222',
    city: 'Rio de Janeiro',
    state: 'RJ',
    linkedIn: 'linkedin.com/in/carlosmendes',
    desiredRole: 'Backend Developer',
    areaOfExpertise: 'API Development',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 6.000 – R$ 8.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Systems Analysis',
    institution: 'UERJ',
    certifications: [],
    languages: ['Portuguese', 'Spanish'],
    professionalSummary: 'Backend developer specialising in Node.js REST APIs and PostgreSQL.',
    keyTechnicalSkills: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    softwareTools: ['VS Code', 'Postman', 'GitHub'],
    mainAchievements: 'Built a payment gateway integration handling 50k transactions/day.',
    resumeFileName: 'carlos-mendes-resume.pdf',
    submittedAt: '2026-06-19T14:05:00Z',
    lastUpdatedAt: '2026-06-20T09:00:00Z',
    status: 'New',
  },
  {
    id: '3',
    fullName: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    phone: '+55 31 97777-3333',
    city: 'Belo Horizonte',
    state: 'MG',
    linkedIn: 'linkedin.com/in/fernandalima',
    desiredRole: 'UX Designer',
    areaOfExpertise: 'Product Design',
    yearsOfExperience: 7,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 9.000 – R$ 12.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Master's",
    courseMajor: 'Design',
    institution: 'UFMG',
    certifications: ['Google UX Design Certificate'],
    languages: ['Portuguese', 'English', 'French'],
    professionalSummary: 'UX designer with 7 years creating user-centred digital products across healthcare and retail.',
    keyTechnicalSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    softwareTools: ['Figma', 'Maze', 'Notion'],
    mainAchievements: 'Redesigned onboarding flow increasing activation rate by 28%.',
    resumeFileName: 'fernanda-lima-resume.pdf',
    submittedAt: '2026-06-20T08:30:00Z',
    lastUpdatedAt: '2026-06-21T11:15:00Z',
    status: 'Approved',
    internalNotes: 'Excellent fit. Offer letter in progress.',
  },
  {
    id: '4',
    fullName: 'Rafael Costa',
    email: 'rafael.costa@email.com',
    phone: '+55 41 96666-4444',
    city: 'Curitiba',
    state: 'PR',
    desiredRole: 'DevOps Engineer',
    areaOfExpertise: 'Cloud Infrastructure',
    yearsOfExperience: 2,
    currentEmploymentStatus: 'Student',
    salaryExpectation: 'R$ 4.000 – R$ 5.500',
    availabilityDate: '2026-07-01',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Technology',
    institution: 'UTFPR',
    certifications: ['AWS Solutions Architect Associate'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Junior DevOps engineer with hands-on experience in CI/CD pipelines and Kubernetes.',
    keyTechnicalSkills: ['Docker', 'Kubernetes', 'Terraform', 'AWS'],
    softwareTools: ['GitHub Actions', 'Grafana', 'Datadog'],
    mainAchievements: 'Implemented GitOps workflow reducing deployment time from 45 min to 8 min.',
    submittedAt: '2026-06-21T16:45:00Z',
    lastUpdatedAt: '2026-06-21T16:45:00Z',
    status: 'Rejected',
    internalNotes: 'Good potential but insufficient experience for current seniority requirement.',
  },
  {
    id: '5',
    fullName: 'Beatriz Santos',
    email: 'beatriz.santos@email.com',
    phone: '+55 51 95555-5555',
    city: 'Porto Alegre',
    state: 'RS',
    linkedIn: 'linkedin.com/in/beatrizsantos',
    desiredRole: 'Data Analyst',
    areaOfExpertise: 'Business Intelligence',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Unemployed',
    salaryExpectation: 'R$ 5.500 – R$ 7.000',
    availabilityDate: '2026-06-30',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Statistics',
    institution: 'UFRGS',
    certifications: ['Google Data Analytics'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Data analyst experienced in building BI dashboards and ETL pipelines for retail companies.',
    keyTechnicalSkills: ['Python', 'SQL', 'Power BI', 'dbt'],
    softwareTools: ['Power BI', 'BigQuery', 'Metabase'],
    mainAchievements: 'Built sales forecasting model that improved inventory accuracy by 22%.',
    resumeFileName: 'beatriz-santos-resume.pdf',
    submittedAt: '2026-06-22T09:00:00Z',
    lastUpdatedAt: '2026-06-22T09:00:00Z',
    status: 'New',
  },
  {
    id: '6',
    fullName: 'Lucas Ferreira',
    email: 'lucas.ferreira@email.com',
    phone: '+55 11 94444-6666',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/lucasferreira',
    desiredRole: 'Full Stack Developer',
    areaOfExpertise: 'Web Development',
    yearsOfExperience: 6,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 10.000 – R$ 13.000',
    availabilityDate: '2026-08-15',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Engineering',
    institution: 'Unicamp',
    certifications: ['AWS Developer Associate', 'MongoDB Certified'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Full stack developer with expertise in React and Node.js, delivering SaaS products at scale.',
    keyTechnicalSkills: ['React', 'Node.js', 'MongoDB', 'GraphQL'],
    softwareTools: ['VS Code', 'Jira', 'Docker'],
    mainAchievements: 'Architected multi-tenant SaaS platform serving 200+ clients with 99.9% uptime.',
    resumeFileName: 'lucas-ferreira-resume.pdf',
    submittedAt: '2026-06-15T11:00:00Z',
    lastUpdatedAt: '2026-06-15T11:00:00Z',
    status: 'Under Review',
  },
  {
    id: '7',
    fullName: 'Mariana Rodrigues',
    email: 'mariana.rodrigues@email.com',
    phone: '+55 61 93333-7777',
    city: 'Brasília',
    state: 'DF',
    linkedIn: 'linkedin.com/in/marianarod',
    desiredRole: 'Product Manager',
    areaOfExpertise: 'Product Management',
    yearsOfExperience: 8,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 14.000 – R$ 18.000',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "MBA",
    courseMajor: 'Business Administration',
    institution: 'FGV',
    certifications: ['Certified Scrum Product Owner', 'Google Project Management'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'Product manager with 8 years leading cross-functional teams in govtech and edtech sectors.',
    keyTechnicalSkills: ['Roadmap Planning', 'OKRs', 'A/B Testing', 'SQL'],
    softwareTools: ['Jira', 'Confluence', 'Mixpanel', 'Figma'],
    mainAchievements: 'Launched digital citizen portal used by 1.2M users in 3 months.',
    resumeFileName: 'mariana-rodrigues-resume.pdf',
    submittedAt: '2026-06-14T09:30:00Z',
    lastUpdatedAt: '2026-06-14T09:30:00Z',
    status: 'Approved',
  },
  {
    id: '8',
    fullName: 'Diego Alves',
    email: 'diego.alves@email.com',
    phone: '+55 71 92222-8888',
    city: 'Salvador',
    state: 'BA',
    desiredRole: 'Mobile Developer',
    areaOfExpertise: 'iOS Development',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 7.000 – R$ 9.000',
    availabilityDate: '2026-07-20',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'UFBA',
    certifications: ['Apple Certified Developer'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'iOS developer with 4 years building native Swift apps for healthcare and logistics clients.',
    keyTechnicalSkills: ['Swift', 'SwiftUI', 'Xcode', 'Core Data'],
    softwareTools: ['Xcode', 'TestFlight', 'Figma'],
    mainAchievements: 'Published 3 apps on App Store with combined 80k downloads.',
    submittedAt: '2026-06-13T15:00:00Z',
    lastUpdatedAt: '2026-06-13T15:00:00Z',
    status: 'New',
  },
  {
    id: '9',
    fullName: 'Juliana Nascimento',
    email: 'juliana.nasc@email.com',
    phone: '+55 81 91111-9999',
    city: 'Recife',
    state: 'PE',
    linkedIn: 'linkedin.com/in/juliananascimento',
    portfolio: 'juliananasc.com',
    desiredRole: 'Data Scientist',
    areaOfExpertise: 'Machine Learning',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 11.000 – R$ 14.000',
    availabilityDate: '2026-09-15',
    preferredWorkModel: 'Remote',
    degreeLevel: "Master's",
    courseMajor: 'Data Science',
    institution: 'UFPE',
    certifications: ['TensorFlow Developer Certificate', 'AWS Machine Learning Specialty'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Data scientist specialising in NLP and recommendation systems for e-commerce.',
    keyTechnicalSkills: ['Python', 'TensorFlow', 'scikit-learn', 'Spark'],
    softwareTools: ['Jupyter', 'MLflow', 'Databricks'],
    mainAchievements: 'Built recommendation engine increasing average order value by 18%.',
    resumeFileName: 'juliana-nasc-resume.pdf',
    submittedAt: '2026-06-12T10:45:00Z',
    lastUpdatedAt: '2026-06-12T10:45:00Z',
    status: 'Under Review',
  },
  {
    id: '10',
    fullName: 'Thiago Barbosa',
    email: 'thiago.barbosa@email.com',
    phone: '+55 85 90000-1010',
    city: 'Fortaleza',
    state: 'CE',
    desiredRole: 'QA Engineer',
    areaOfExpertise: 'Test Automation',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 5.000 – R$ 6.500',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Systems',
    institution: 'UFC',
    certifications: ['ISTQB Foundation Level'],
    languages: ['Portuguese'],
    professionalSummary: 'QA engineer with 3 years building automated test suites for web and mobile applications.',
    keyTechnicalSkills: ['Selenium', 'Cypress', 'Playwright', 'Jest'],
    softwareTools: ['Jira', 'TestRail', 'GitHub Actions'],
    mainAchievements: 'Reduced regression testing time by 70% through comprehensive Cypress automation.',
    submittedAt: '2026-06-11T08:00:00Z',
    lastUpdatedAt: '2026-06-11T08:00:00Z',
    status: 'Rejected',
  },
  {
    id: '11',
    fullName: 'Camila Pinto',
    email: 'camila.pinto@email.com',
    phone: '+55 11 98877-1111',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/camilapinto',
    desiredRole: 'UI Designer',
    areaOfExpertise: 'Visual Design',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 5.000 – R$ 7.000',
    availabilityDate: '2026-07-10',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Graphic Design',
    institution: 'FAAP',
    certifications: ['Adobe Certified Professional'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'UI designer creating visually compelling interfaces for mobile and web apps.',
    keyTechnicalSkills: ['Figma', 'Adobe XD', 'Illustrator', 'Photoshop'],
    softwareTools: ['Figma', 'Zeplin', 'Notion'],
    mainAchievements: 'Delivered design system adopted by 4 product teams across the company.',
    submittedAt: '2026-06-10T14:20:00Z',
    lastUpdatedAt: '2026-06-10T14:20:00Z',
    status: 'New',
  },
  {
    id: '12',
    fullName: 'Pedro Gomes',
    email: 'pedro.gomes@email.com',
    phone: '+55 31 97766-2222',
    city: 'Belo Horizonte',
    state: 'MG',
    linkedIn: 'linkedin.com/in/pedrogomes',
    desiredRole: 'Cloud Architect',
    areaOfExpertise: 'Cloud Computing',
    yearsOfExperience: 10,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 18.000 – R$ 22.000',
    availabilityDate: '2026-11-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Master's",
    courseMajor: 'Computer Networks',
    institution: 'PUC Minas',
    certifications: ['AWS Solutions Architect Professional', 'Google Cloud Professional', 'Azure Solutions Architect'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Cloud architect with 10 years designing and migrating enterprise systems to AWS and GCP.',
    keyTechnicalSkills: ['AWS', 'GCP', 'Terraform', 'Kubernetes', 'Microservices'],
    softwareTools: ['Terraform', 'Ansible', 'Grafana', 'Datadog'],
    mainAchievements: 'Led cloud migration of 200-service monolith saving R$2M/year in infrastructure costs.',
    resumeFileName: 'pedro-gomes-resume.pdf',
    submittedAt: '2026-06-09T09:00:00Z',
    lastUpdatedAt: '2026-06-09T09:00:00Z',
    status: 'Approved',
  },
  {
    id: '13',
    fullName: 'Isabella Cardoso',
    email: 'isabella.cardoso@email.com',
    phone: '+55 41 96655-3333',
    city: 'Curitiba',
    state: 'PR',
    desiredRole: 'Business Analyst',
    areaOfExpertise: 'Business Analysis',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 7.000 – R$ 9.000',
    availabilityDate: '2026-08-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Business Administration',
    institution: 'UFPR',
    certifications: ['CBAP', 'PMI-PBA'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'Business analyst bridging the gap between stakeholders and tech teams in agile environments.',
    keyTechnicalSkills: ['Requirements Elicitation', 'Process Mapping', 'SQL', 'BPMN'],
    softwareTools: ['Jira', 'Confluence', 'Lucidchart', 'Excel'],
    mainAchievements: 'Documented and streamlined procurement process reducing cycle time by 35%.',
    submittedAt: '2026-06-08T11:30:00Z',
    lastUpdatedAt: '2026-06-08T11:30:00Z',
    status: 'Under Review',
  },
  {
    id: '14',
    fullName: 'Rodrigo Teixeira',
    email: 'rodrigo.teixeira@email.com',
    phone: '+55 51 95544-4444',
    city: 'Porto Alegre',
    state: 'RS',
    linkedIn: 'linkedin.com/in/rodrigoteixeira',
    desiredRole: 'Android Developer',
    areaOfExpertise: 'Mobile Development',
    yearsOfExperience: 6,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 9.000 – R$ 12.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'PUCRS',
    certifications: ['Google Associate Android Developer'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Android developer building high-performance Kotlin apps for fintech and retail sectors.',
    keyTechnicalSkills: ['Kotlin', 'Jetpack Compose', 'Coroutines', 'Room'],
    softwareTools: ['Android Studio', 'Firebase', 'GitHub'],
    mainAchievements: 'Rebuilt legacy Java app in Kotlin reducing crash rate from 3.2% to 0.1%.',
    resumeFileName: 'rodrigo-teixeira-resume.pdf',
    submittedAt: '2026-06-07T13:00:00Z',
    lastUpdatedAt: '2026-06-07T13:00:00Z',
    status: 'New',
  },
  {
    id: '15',
    fullName: 'Larissa Monteiro',
    email: 'larissa.monteiro@email.com',
    phone: '+55 61 94433-5555',
    city: 'Brasília',
    state: 'DF',
    desiredRole: 'Scrum Master',
    areaOfExpertise: 'Agile Coaching',
    yearsOfExperience: 7,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 10.000 – R$ 13.000',
    availabilityDate: '2026-10-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Production Engineering',
    institution: 'UnB',
    certifications: ['CSM', 'PSM II', 'SAFe Agilist'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Certified Scrum Master coaching 4 agile teams across fintech and logistics domains.',
    keyTechnicalSkills: ['Scrum', 'Kanban', 'OKRs', 'Facilitation'],
    softwareTools: ['Jira', 'Miro', 'Confluence', 'Slack'],
    mainAchievements: 'Improved team velocity by 40% in 6 months through focused retrospectives and impediment removal.',
    submittedAt: '2026-06-06T10:00:00Z',
    lastUpdatedAt: '2026-06-06T10:00:00Z',
    status: 'Rejected',
  },
  {
    id: '16',
    fullName: 'Gabriel Souza',
    email: 'gabriel.souza@email.com',
    phone: '+55 21 93322-6666',
    city: 'Rio de Janeiro',
    state: 'RJ',
    linkedIn: 'linkedin.com/in/gabrielsouza',
    portfolio: 'gabrielsouza.io',
    desiredRole: 'Security Engineer',
    areaOfExpertise: 'Cybersecurity',
    yearsOfExperience: 6,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 12.000 – R$ 15.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Security',
    institution: 'PUC-Rio',
    certifications: ['CEH', 'CISSP', 'CompTIA Security+'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Security engineer specialising in penetration testing and SIEM implementation for banks.',
    keyTechnicalSkills: ['Penetration Testing', 'SIEM', 'ISO 27001', 'Vulnerability Management'],
    softwareTools: ['Kali Linux', 'Burp Suite', 'Splunk', 'Nessus'],
    mainAchievements: 'Identified and remediated 12 critical vulnerabilities preventing potential R$5M breach.',
    submittedAt: '2026-06-05T09:15:00Z',
    lastUpdatedAt: '2026-06-05T09:15:00Z',
    status: 'Under Review',
  },
  {
    id: '17',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    phone: '+55 11 92211-7777',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/priyasharma',
    desiredRole: 'Machine Learning Engineer',
    areaOfExpertise: 'AI / ML',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 13.000 – R$ 16.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Master's",
    courseMajor: 'Artificial Intelligence',
    institution: 'IIT Bombay',
    certifications: ['Deep Learning Specialization', 'GCP Professional ML Engineer'],
    languages: ['English', 'Portuguese', 'Hindi'],
    professionalSummary: 'ML engineer building production LLM pipelines and computer vision systems for retail clients.',
    keyTechnicalSkills: ['PyTorch', 'LangChain', 'MLflow', 'Computer Vision'],
    softwareTools: ['Jupyter', 'Weights & Biases', 'Docker', 'Vertex AI'],
    mainAchievements: 'Deployed real-time product recognition model with 96% accuracy across 500 SKUs.',
    resumeFileName: 'priya-sharma-resume.pdf',
    submittedAt: '2026-06-04T14:30:00Z',
    lastUpdatedAt: '2026-06-04T14:30:00Z',
    status: 'New',
  },
  {
    id: '18',
    fullName: 'Eduardo Ramos',
    email: 'eduardo.ramos@email.com',
    phone: '+55 71 91100-8888',
    city: 'Salvador',
    state: 'BA',
    desiredRole: 'Database Administrator',
    areaOfExpertise: 'Database Engineering',
    yearsOfExperience: 9,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 10.000 – R$ 13.000',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Systems',
    institution: 'UFBA',
    certifications: ['Oracle DBA Certified', 'Microsoft SQL Server Specialist'],
    languages: ['Portuguese'],
    professionalSummary: 'Senior DBA managing mission-critical Oracle and PostgreSQL databases for government agencies.',
    keyTechnicalSkills: ['Oracle DB', 'PostgreSQL', 'MySQL', 'Performance Tuning'],
    softwareTools: ['Oracle Enterprise Manager', 'pgAdmin', 'Toad'],
    mainAchievements: 'Optimised queries in national registry system reducing average response time by 65%.',
    submittedAt: '2026-06-03T08:45:00Z',
    lastUpdatedAt: '2026-06-03T08:45:00Z',
    status: 'Under Review',
  },
  {
    id: '19',
    fullName: 'Sofia Pereira',
    email: 'sofia.pereira@email.com',
    phone: '+55 81 90099-9999',
    city: 'Recife',
    state: 'PE',
    linkedIn: 'linkedin.com/in/sofiapereira',
    desiredRole: 'Technical Writer',
    areaOfExpertise: 'Documentation & Content',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 4.500 – R$ 6.000',
    availabilityDate: '2026-07-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Journalism',
    institution: 'UFPE',
    certifications: ['Google Technical Writing Certificate'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'Technical writer creating developer documentation, API references, and user guides for SaaS companies.',
    keyTechnicalSkills: ['API Documentation', 'Markdown', 'Docs-as-Code', 'OpenAPI'],
    softwareTools: ['Notion', 'Docusaurus', 'Stoplight', 'GitHub'],
    mainAchievements: 'Wrote complete API docs for a fintech platform reducing support tickets by 30%.',
    submittedAt: '2026-06-02T12:00:00Z',
    lastUpdatedAt: '2026-06-02T12:00:00Z',
    status: 'Approved',
  },
  {
    id: '20',
    fullName: 'Henrique Castro',
    email: 'henrique.castro@email.com',
    phone: '+55 85 98800-0101',
    city: 'Fortaleza',
    state: 'CE',
    desiredRole: 'Embedded Systems Engineer',
    areaOfExpertise: 'Firmware Development',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 8.000 – R$ 10.500',
    availabilityDate: '2026-09-15',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Electrical Engineering',
    institution: 'UFC',
    certifications: ['ARM Cortex-M Specialist'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Embedded systems engineer designing firmware for IoT devices in industrial and agricultural sectors.',
    keyTechnicalSkills: ['C', 'C++', 'RTOS', 'ARM Cortex-M', 'CAN Bus'],
    softwareTools: ['Keil MDK', 'STM32CubeIDE', 'JTAG Debugger'],
    mainAchievements: 'Developed low-power soil sensor firmware extending battery life from 3 to 18 months.',
    submittedAt: '2026-06-01T10:30:00Z',
    lastUpdatedAt: '2026-06-01T10:30:00Z',
    status: 'New',
  },
  {
    id: '21',
    fullName: 'Amanda Freitas',
    email: 'amanda.freitas@email.com',
    phone: '+55 11 97799-2121',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/amandafreitas',
    desiredRole: 'React Native Developer',
    areaOfExpertise: 'Cross-platform Mobile',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 7.000 – R$ 9.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'Mackenzie',
    certifications: [],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'React Native developer shipping cross-platform apps for logistics and healthcare startups.',
    keyTechnicalSkills: ['React Native', 'Expo', 'TypeScript', 'Redux'],
    softwareTools: ['Expo', 'Flipper', 'Firebase', 'GitHub'],
    mainAchievements: 'Released field operations app used by 1,500 delivery drivers daily.',
    submittedAt: '2026-05-31T09:00:00Z',
    lastUpdatedAt: '2026-05-31T09:00:00Z',
    status: 'Under Review',
  },
  {
    id: '22',
    fullName: 'Gustavo Leal',
    email: 'gustavo.leal@email.com',
    phone: '+55 31 96688-2222',
    city: 'Belo Horizonte',
    state: 'MG',
    desiredRole: 'Systems Analyst',
    areaOfExpertise: 'Enterprise Systems',
    yearsOfExperience: 8,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 9.000 – R$ 11.000',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Systems',
    institution: 'UFMG',
    certifications: ['SAP Certified Associate', 'ITIL Foundation'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Systems analyst with SAP expertise delivering ERP implementations for manufacturing companies.',
    keyTechnicalSkills: ['SAP S/4HANA', 'ABAP', 'Business Process Design', 'SQL'],
    softwareTools: ['SAP', 'ServiceNow', 'JIRA'],
    mainAchievements: 'Led SAP S/4HANA rollout for 800-employee manufacturing plant on time and under budget.',
    submittedAt: '2026-05-30T14:00:00Z',
    lastUpdatedAt: '2026-05-30T14:00:00Z',
    status: 'Rejected',
  },
  {
    id: '23',
    fullName: 'Natalia Vasconcelos',
    email: 'natalia.vasc@email.com',
    phone: '+55 41 95577-3333',
    city: 'Curitiba',
    state: 'PR',
    linkedIn: 'linkedin.com/in/nataliavasc',
    portfolio: 'nataliavasc.com',
    desiredRole: 'Motion Designer',
    areaOfExpertise: 'Motion & Animation',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 6.000 – R$ 8.000',
    availabilityDate: '2026-07-15',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Digital Animation',
    institution: 'UP',
    certifications: ['Adobe After Effects Certified'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Motion designer crafting animations for product launches, explainer videos, and social campaigns.',
    keyTechnicalSkills: ['After Effects', 'Cinema 4D', 'Premiere Pro', 'Lottie'],
    softwareTools: ['After Effects', 'Cinema 4D', 'Figma'],
    mainAchievements: 'Produced campaign animations that generated 4M+ organic views on social media.',
    submittedAt: '2026-05-29T10:00:00Z',
    lastUpdatedAt: '2026-05-29T10:00:00Z',
    status: 'New',
  },
  {
    id: '24',
    fullName: 'Felipe Araujo',
    email: 'felipe.araujo@email.com',
    phone: '+55 51 94466-4444',
    city: 'Porto Alegre',
    state: 'RS',
    desiredRole: 'Site Reliability Engineer',
    areaOfExpertise: 'SRE / Platform Engineering',
    yearsOfExperience: 7,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 14.000 – R$ 17.000',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Engineering',
    institution: 'UFRGS',
    certifications: ['CKA', 'AWS DevOps Professional'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'SRE engineer building observable, resilient distributed systems for high-traffic e-commerce platforms.',
    keyTechnicalSkills: ['Kubernetes', 'Prometheus', 'Grafana', 'Go', 'Terraform'],
    softwareTools: ['Grafana', 'PagerDuty', 'ArgoCD', 'Helm'],
    mainAchievements: 'Achieved 99.99% uptime SLA on Black Friday traffic spike of 8x normal load.',
    submittedAt: '2026-05-28T08:30:00Z',
    lastUpdatedAt: '2026-05-28T08:30:00Z',
    status: 'Approved',
  },
  {
    id: '25',
    fullName: 'Aisha Diallo',
    email: 'aisha.diallo@email.com',
    phone: '+55 61 93355-5555',
    city: 'Brasília',
    state: 'DF',
    linkedIn: 'linkedin.com/in/aishadi',
    desiredRole: 'HR Tech Analyst',
    areaOfExpertise: 'HR Technology',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 6.500 – R$ 8.500',
    availabilityDate: '2026-08-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Human Resources',
    institution: 'UniCEUB',
    certifications: ['Workday HCM Certified', 'PHR'],
    languages: ['Portuguese', 'English', 'French'],
    professionalSummary: 'HR tech analyst implementing and optimising HRIS platforms for mid-size organisations.',
    keyTechnicalSkills: ['Workday', 'SAP SuccessFactors', 'Power BI', 'Process Automation'],
    softwareTools: ['Workday', 'Power BI', 'Excel', 'Slack'],
    mainAchievements: 'Automated onboarding process reducing new-hire time-to-productivity from 30 to 12 days.',
    submittedAt: '2026-05-27T11:00:00Z',
    lastUpdatedAt: '2026-05-27T11:00:00Z',
    status: 'Under Review',
  },
  {
    id: '26',
    fullName: 'Victor Cunha',
    email: 'victor.cunha@email.com',
    phone: '+55 21 92244-6666',
    city: 'Rio de Janeiro',
    state: 'RJ',
    desiredRole: 'Blockchain Developer',
    areaOfExpertise: 'Web3 / Blockchain',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 10.000 – R$ 14.000',
    availabilityDate: '2026-07-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'UFRJ',
    certifications: ['Ethereum Certified Developer'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Blockchain developer building DeFi protocols and NFT marketplaces on Ethereum and Solana.',
    keyTechnicalSkills: ['Solidity', 'Rust', 'Hardhat', 'Web3.js', 'IPFS'],
    softwareTools: ['Hardhat', 'Remix IDE', 'MetaMask', 'GitHub'],
    mainAchievements: 'Deployed AMM DEX handling $2M+ in daily volume with zero exploits.',
    submittedAt: '2026-05-26T16:00:00Z',
    lastUpdatedAt: '2026-05-26T16:00:00Z',
    status: 'New',
  },
  {
    id: '27',
    fullName: 'Rebeca Azevedo',
    email: 'rebeca.azevedo@email.com',
    phone: '+55 11 91133-7777',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/rebecaaz',
    desiredRole: 'Customer Success Manager',
    areaOfExpertise: 'Customer Success',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 7.500 – R$ 9.500',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Business Administration',
    institution: 'FEI',
    certifications: ['Gainsight Certified', 'HubSpot CRM Certified'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'CS manager driving retention and expansion revenue for a SaaS HR platform with 300+ enterprise accounts.',
    keyTechnicalSkills: ['Churn Analysis', 'QBR Facilitation', 'CRM', 'NPS Programs'],
    softwareTools: ['Gainsight', 'HubSpot', 'Zendesk', 'Looker'],
    mainAchievements: 'Grew net revenue retention from 94% to 112% in 18 months.',
    submittedAt: '2026-05-25T09:30:00Z',
    lastUpdatedAt: '2026-05-25T09:30:00Z',
    status: 'Under Review',
  },
  {
    id: '28',
    fullName: 'Mateus Rocha',
    email: 'mateus.rocha@email.com',
    phone: '+55 71 90022-8888',
    city: 'Salvador',
    state: 'BA',
    desiredRole: 'Game Developer',
    areaOfExpertise: 'Game Development',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 7.000 – R$ 9.500',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Game Design',
    institution: 'UNIJORGE',
    certifications: ['Unity Certified Developer'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Game developer shipping 2D and 3D Unity games for PC and mobile platforms.',
    keyTechnicalSkills: ['Unity', 'C#', 'Shader Graph', 'Photon Networking'],
    softwareTools: ['Unity', 'Blender', 'Git', 'Jira'],
    mainAchievements: 'Published casual mobile game with 150k downloads and 4.5-star rating.',
    submittedAt: '2026-05-24T13:00:00Z',
    lastUpdatedAt: '2026-05-24T13:00:00Z',
    status: 'Approved',
  },
  {
    id: '29',
    fullName: 'Tatiane Moreira',
    email: 'tatiane.moreira@email.com',
    phone: '+55 81 99911-9292',
    city: 'Recife',
    state: 'PE',
    desiredRole: 'IT Project Manager',
    areaOfExpertise: 'Project Management',
    yearsOfExperience: 9,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 13.000 – R$ 16.000',
    availabilityDate: '2026-11-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "MBA",
    courseMajor: 'Project Management',
    institution: 'FGV Online',
    certifications: ['PMP', 'PMI-ACP', 'PRINCE2 Practitioner'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'IT project manager overseeing digital transformation programs for telecoms and banking clients.',
    keyTechnicalSkills: ['MS Project', 'Risk Management', 'Stakeholder Management', 'Agile at Scale'],
    softwareTools: ['MS Project', 'Smartsheet', 'Jira', 'Teams'],
    mainAchievements: 'Delivered core banking system replacement for 2M-customer bank on time with 0 critical incidents.',
    submittedAt: '2026-05-23T08:00:00Z',
    lastUpdatedAt: '2026-05-23T08:00:00Z',
    status: 'Rejected',
  },
  {
    id: '30',
    fullName: 'Bruno Cavalcanti',
    email: 'bruno.cavalcanti@email.com',
    phone: '+55 85 98833-0303',
    city: 'Fortaleza',
    state: 'CE',
    linkedIn: 'linkedin.com/in/brunocavalcanti',
    desiredRole: 'Data Engineer',
    areaOfExpertise: 'Data Platform Engineering',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 11.000 – R$ 14.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'UFC',
    certifications: ['dbt Certified Developer', 'Databricks Data Engineer Associate'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Data engineer building scalable ELT pipelines and data lakes for e-commerce and adtech companies.',
    keyTechnicalSkills: ['Python', 'dbt', 'Spark', 'Airflow', 'BigQuery'],
    softwareTools: ['Databricks', 'Airflow', 'dbt', 'Looker'],
    mainAchievements: 'Reduced data pipeline latency from 6 hours to 15 minutes using event-driven architecture.',
    resumeFileName: 'bruno-cavalcanti-resume.pdf',
    submittedAt: '2026-05-22T10:00:00Z',
    lastUpdatedAt: '2026-05-22T10:00:00Z',
    status: 'New',
  },
  {
    id: '31',
    fullName: 'Renata Xavier',
    email: 'renata.xavier@email.com',
    phone: '+55 11 96622-3131',
    city: 'São Paulo',
    state: 'SP',
    desiredRole: 'Product Designer',
    areaOfExpertise: 'Product Design',
    yearsOfExperience: 6,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 10.000 – R$ 13.000',
    availabilityDate: '2026-09-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Industrial Design',
    institution: 'ESPM',
    certifications: ['Figma Advanced Certification'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Product designer crafting end-to-end digital experiences from discovery to delivery in B2B SaaS.',
    keyTechnicalSkills: ['Figma', 'Design Thinking', 'Usability Testing', 'Design Systems'],
    softwareTools: ['Figma', 'Hotjar', 'FullStory', 'Notion'],
    mainAchievements: 'Redesigned checkout flow reducing cart abandonment by 32%.',
    submittedAt: '2026-05-21T14:00:00Z',
    lastUpdatedAt: '2026-05-21T14:00:00Z',
    status: 'Under Review',
  },
  {
    id: '32',
    fullName: 'Jonas Batista',
    email: 'jonas.batista@email.com',
    phone: '+55 31 95511-3232',
    city: 'Belo Horizonte',
    state: 'MG',
    desiredRole: 'Network Engineer',
    areaOfExpertise: 'Network Infrastructure',
    yearsOfExperience: 8,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 10.000 – R$ 12.000',
    availabilityDate: '2026-10-15',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Telecommunications',
    institution: 'CEFET-MG',
    certifications: ['CCNP Enterprise', 'CompTIA Network+'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Network engineer designing and maintaining enterprise LAN/WAN infrastructure for mining and energy companies.',
    keyTechnicalSkills: ['Cisco Routing & Switching', 'BGP', 'MPLS', 'SD-WAN', 'Firewall'],
    softwareTools: ['Cisco DNA Center', 'SolarWinds', 'Wireshark'],
    mainAchievements: 'Designed SD-WAN solution for 40-branch company reducing WAN costs by 45%.',
    submittedAt: '2026-05-20T09:00:00Z',
    lastUpdatedAt: '2026-05-20T09:00:00Z',
    status: 'New',
  },
  {
    id: '33',
    fullName: 'Vanessa Melo',
    email: 'vanessa.melo@email.com',
    phone: '+55 41 94400-3333',
    city: 'Curitiba',
    state: 'PR',
    linkedIn: 'linkedin.com/in/vanessamelo',
    desiredRole: 'Content Strategist',
    areaOfExpertise: 'Content & SEO',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 5.500 – R$ 7.500',
    availabilityDate: '2026-07-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Marketing',
    institution: 'PUC-PR',
    certifications: ['HubSpot Content Marketing', 'Google Analytics 4'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'Content strategist growing organic traffic through SEO-led editorial and lifecycle content programs.',
    keyTechnicalSkills: ['SEO', 'Content Strategy', 'Copywriting', 'Analytics'],
    softwareTools: ['HubSpot', 'Semrush', 'Ahrefs', 'WordPress'],
    mainAchievements: 'Grew organic sessions from 20k to 180k/month in 12 months through content hub strategy.',
    submittedAt: '2026-05-19T11:00:00Z',
    lastUpdatedAt: '2026-05-19T11:00:00Z',
    status: 'Rejected',
  },
  {
    id: '34',
    fullName: 'Arthur Campos',
    email: 'arthur.campos@email.com',
    phone: '+55 51 93399-3434',
    city: 'Porto Alegre',
    state: 'RS',
    desiredRole: 'Python Developer',
    areaOfExpertise: 'Backend / Automation',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 8.000 – R$ 10.000',
    availabilityDate: '2026-08-15',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'PUCRS',
    certifications: ['Python Institute PCEP'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Python developer building automation tools, data pipelines, and REST APIs for logistics companies.',
    keyTechnicalSkills: ['Python', 'FastAPI', 'Celery', 'Redis', 'PostgreSQL'],
    softwareTools: ['VS Code', 'Docker', 'GitHub Actions', 'Postman'],
    mainAchievements: 'Automated invoice processing pipeline saving 200 manual hours per month.',
    resumeFileName: 'arthur-campos-resume.pdf',
    submittedAt: '2026-05-18T15:00:00Z',
    lastUpdatedAt: '2026-05-18T15:00:00Z',
    status: 'Under Review',
  },
  {
    id: '35',
    fullName: 'Monique Fonseca',
    email: 'monique.fonseca@email.com',
    phone: '+55 61 92288-3535',
    city: 'Brasília',
    state: 'DF',
    desiredRole: 'Salesforce Developer',
    areaOfExpertise: 'CRM Development',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 10.000 – R$ 13.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Systems',
    institution: 'UCB',
    certifications: ['Salesforce Platform Developer II', 'Salesforce Admin'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Salesforce developer implementing Sales Cloud and Service Cloud solutions for enterprise clients.',
    keyTechnicalSkills: ['Apex', 'LWC', 'SOQL', 'Flow Builder', 'Salesforce API'],
    softwareTools: ['Salesforce', 'VS Code', 'Workbench', 'Jira'],
    mainAchievements: 'Built custom CPQ solution reducing quote generation time from 2 days to 15 minutes.',
    submittedAt: '2026-05-17T10:00:00Z',
    lastUpdatedAt: '2026-05-17T10:00:00Z',
    status: 'New',
  },
  {
    id: '36',
    fullName: 'Leonardo Duarte',
    email: 'leonardo.duarte@email.com',
    phone: '+55 21 91177-3636',
    city: 'Rio de Janeiro',
    state: 'RJ',
    linkedIn: 'linkedin.com/in/leonardoduarte',
    desiredRole: 'Solutions Architect',
    areaOfExpertise: 'Enterprise Architecture',
    yearsOfExperience: 12,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 20.000 – R$ 25.000',
    availabilityDate: '2026-12-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Master's",
    courseMajor: 'Software Engineering',
    institution: 'IME-RJ',
    certifications: ['AWS Solutions Architect Professional', 'TOGAF 9', 'GCP Professional Cloud Architect'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Solutions architect designing cloud-native enterprise architectures for banking and insurance sectors.',
    keyTechnicalSkills: ['Enterprise Architecture', 'Microservices', 'Event-Driven Architecture', 'AWS', 'GCP'],
    softwareTools: ['ArchiMate', 'Lucidchart', 'Terraform', 'Confluence'],
    mainAchievements: 'Architected platform processing R$10B in annual transactions with 5-nines reliability.',
    resumeFileName: 'leonardo-duarte-resume.pdf',
    submittedAt: '2026-05-16T09:00:00Z',
    lastUpdatedAt: '2026-05-16T09:00:00Z',
    status: 'Approved',
  },
  {
    id: '37',
    fullName: 'Paloma Ribeiro',
    email: 'paloma.ribeiro@email.com',
    phone: '+55 11 90066-3737',
    city: 'São Paulo',
    state: 'SP',
    desiredRole: 'Digital Marketing Analyst',
    areaOfExpertise: 'Performance Marketing',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 6.000 – R$ 8.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Marketing',
    institution: 'ESPM',
    certifications: ['Google Ads Certified', 'Meta Blueprint Certified'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Performance marketing analyst managing R$500k/month in paid media budgets across Google and Meta.',
    keyTechnicalSkills: ['Google Ads', 'Meta Ads', 'GA4', 'Data Studio', 'CRO'],
    softwareTools: ['Google Ads', 'Meta Business Suite', 'Looker Studio', 'Hotjar'],
    mainAchievements: 'Reduced customer acquisition cost by 38% through systematic creative testing program.',
    submittedAt: '2026-05-15T14:30:00Z',
    lastUpdatedAt: '2026-05-15T14:30:00Z',
    status: 'Under Review',
  },
  {
    id: '38',
    fullName: 'Caio Nunes',
    email: 'caio.nunes@email.com',
    phone: '+55 71 99955-3838',
    city: 'Salvador',
    state: 'BA',
    desiredRole: 'Java Developer',
    areaOfExpertise: 'Enterprise Java',
    yearsOfExperience: 7,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 11.000 – R$ 14.000',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'UFBA',
    certifications: ['Oracle Java SE 17 Developer', 'Spring Professional'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Senior Java developer building microservices and event-driven backends for banking and insurance.',
    keyTechnicalSkills: ['Java', 'Spring Boot', 'Kafka', 'Hibernate', 'Docker'],
    softwareTools: ['IntelliJ IDEA', 'Maven', 'Kafka', 'GitHub'],
    mainAchievements: 'Modernised monolithic insurance system to 12 microservices reducing deployment frequency from quarterly to daily.',
    submittedAt: '2026-05-14T08:30:00Z',
    lastUpdatedAt: '2026-05-14T08:30:00Z',
    status: 'New',
  },
  {
    id: '39',
    fullName: 'Elisa Tavares',
    email: 'elisa.tavares@email.com',
    phone: '+55 81 98844-3939',
    city: 'Recife',
    state: 'PE',
    linkedIn: 'linkedin.com/in/elisatavares',
    desiredRole: 'Research Scientist',
    areaOfExpertise: 'Applied AI Research',
    yearsOfExperience: 6,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 16.000 – R$ 20.000',
    availabilityDate: '2026-11-01',
    preferredWorkModel: 'Remote',
    degreeLevel: 'PhD',
    courseMajor: 'Computer Science',
    institution: 'CIn/UFPE',
    certifications: ['NeurIPS 2024 Presenter'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'AI research scientist publishing on transformer efficiency, working at the intersection of academia and industry.',
    keyTechnicalSkills: ['PyTorch', 'Transformers', 'RLHF', 'Distributed Training', 'Research Methods'],
    softwareTools: ['PyTorch', 'HuggingFace', 'W&B', 'LaTeX'],
    mainAchievements: '4 papers published at NeurIPS and ICLR; 500+ citations on Google Scholar.',
    resumeFileName: 'elisa-tavares-cv.pdf',
    submittedAt: '2026-05-13T12:00:00Z',
    lastUpdatedAt: '2026-05-13T12:00:00Z',
    status: 'Under Review',
  },
  {
    id: '40',
    fullName: 'Tiago Andrade',
    email: 'tiago.andrade@email.com',
    phone: '+55 85 97733-4040',
    city: 'Fortaleza',
    state: 'CE',
    desiredRole: 'IT Support Specialist',
    areaOfExpertise: 'Technical Support',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 3.500 – R$ 4.500',
    availabilityDate: '2026-07-01',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Technology',
    institution: 'IFCE',
    certifications: ['CompTIA A+', 'ITIL Foundation'],
    languages: ['Portuguese'],
    professionalSummary: 'IT support specialist providing Tier 1 and Tier 2 support for 500+ endpoints at a regional retail chain.',
    keyTechnicalSkills: ['Windows Server', 'Active Directory', 'Office 365', 'Networking Basics'],
    softwareTools: ['ServiceNow', 'TeamViewer', 'Active Directory'],
    mainAchievements: 'Achieved 97% SLA compliance for ticket resolution over 12 consecutive months.',
    submittedAt: '2026-05-12T10:00:00Z',
    lastUpdatedAt: '2026-05-12T10:00:00Z',
    status: 'Rejected',
  },
  {
    id: '41',
    fullName: 'Luana Carvalho',
    email: 'luana.carvalho@email.com',
    phone: '+55 11 95566-4141',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/luanacarvalho',
    desiredRole: 'Growth Analyst',
    areaOfExpertise: 'Growth & Product Analytics',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 7.000 – R$ 9.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Economics',
    institution: 'FEA-USP',
    certifications: ['Amplitude Analytics Certified', 'Google Analytics 4'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Growth analyst running experimentation programs and funnel optimisation for a leading edtech platform.',
    keyTechnicalSkills: ['A/B Testing', 'SQL', 'Python', 'Funnel Analysis', 'Cohort Analysis'],
    softwareTools: ['Amplitude', 'Mixpanel', 'Looker', 'BigQuery'],
    mainAchievements: 'Increased free-to-paid conversion rate by 14% through 22 sequential experiments.',
    submittedAt: '2026-05-11T09:00:00Z',
    lastUpdatedAt: '2026-05-11T09:00:00Z',
    status: 'New',
  },
  {
    id: '42',
    fullName: 'Marcelo Vieira',
    email: 'marcelo.vieira@email.com',
    phone: '+55 31 94455-4242',
    city: 'Belo Horizonte',
    state: 'MG',
    desiredRole: '.NET Developer',
    areaOfExpertise: 'Enterprise .NET',
    yearsOfExperience: 8,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 11.000 – R$ 14.000',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Engineering',
    institution: 'UFMG',
    certifications: ['Microsoft Azure Developer Associate', 'AZ-900'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Senior .NET developer building scalable C# microservices and Azure cloud solutions for healthcare.',
    keyTechnicalSkills: ['C#', '.NET 8', 'Azure', 'Entity Framework', 'gRPC'],
    softwareTools: ['Visual Studio', 'Azure DevOps', 'Docker', 'Postman'],
    mainAchievements: 'Re-platformed hospital management system to Azure reducing infrastructure costs by R$800k/year.',
    submittedAt: '2026-05-10T08:00:00Z',
    lastUpdatedAt: '2026-05-10T08:00:00Z',
    status: 'Under Review',
  },
  {
    id: '43',
    fullName: 'Patrícia Silveira',
    email: 'patricia.silveira@email.com',
    phone: '+55 41 93344-4343',
    city: 'Curitiba',
    state: 'PR',
    desiredRole: 'People Analytics Specialist',
    areaOfExpertise: 'People Analytics',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 8.000 – R$ 10.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Master's",
    courseMajor: 'Organizational Psychology',
    institution: 'PUC-PR',
    certifications: ['SHRM-CP', 'Power BI Data Analyst'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'People analytics specialist translating HR data into workforce insights that drive business decisions.',
    keyTechnicalSkills: ['Power BI', 'SQL', 'Python', 'Statistical Analysis', 'Predictive Modelling'],
    softwareTools: ['Power BI', 'Workday', 'Python', 'Excel'],
    mainAchievements: 'Built attrition prediction model with 82% accuracy enabling proactive retention interventions.',
    submittedAt: '2026-05-09T11:00:00Z',
    lastUpdatedAt: '2026-05-09T11:00:00Z',
    status: 'Approved',
  },
  {
    id: '44',
    fullName: 'Davi Matos',
    email: 'davi.matos@email.com',
    phone: '+55 51 92233-4444',
    city: 'Porto Alegre',
    state: 'RS',
    desiredRole: 'AR/VR Developer',
    areaOfExpertise: 'Immersive Technology',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 8.000 – R$ 11.000',
    availabilityDate: '2026-07-15',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'UFRGS',
    certifications: ['Unity VR Developer Certified'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'AR/VR developer building industrial training simulations and retail try-on experiences in Unity and Unreal.',
    keyTechnicalSkills: ['Unity', 'Unreal Engine', 'C#', 'ARKit', 'OpenXR'],
    softwareTools: ['Unity', 'Unreal Engine', 'Blender', 'Houdini'],
    mainAchievements: 'Built VR safety training used by 3k oil-rig workers, reducing on-site accidents by 60%.',
    submittedAt: '2026-05-08T14:00:00Z',
    lastUpdatedAt: '2026-05-08T14:00:00Z',
    status: 'New',
  },
  {
    id: '45',
    fullName: 'Samira Oliveira',
    email: 'samira.oliveira@email.com',
    phone: '+55 61 91122-4545',
    city: 'Brasília',
    state: 'DF',
    linkedIn: 'linkedin.com/in/samiraoliv',
    desiredRole: 'Compliance Analyst',
    areaOfExpertise: 'Regulatory Compliance',
    yearsOfExperience: 6,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 9.000 – R$ 11.500',
    availabilityDate: '2026-10-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Law',
    institution: 'UnB',
    certifications: ['CIPP/E', 'ISO 27701 Lead Implementer'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Compliance analyst ensuring LGPD and GDPR adherence for fintech and healthtech organisations.',
    keyTechnicalSkills: ['LGPD', 'GDPR', 'Risk Assessment', 'Privacy by Design', 'Data Mapping'],
    softwareTools: ['OneTrust', 'Jira', 'Confluence'],
    mainAchievements: 'Led LGPD compliance programme achieving full certification with zero critical findings in audit.',
    submittedAt: '2026-05-07T09:00:00Z',
    lastUpdatedAt: '2026-05-07T09:00:00Z',
    status: 'Under Review',
  },
  {
    id: '46',
    fullName: 'Paulo Figueiredo',
    email: 'paulo.figueiredo@email.com',
    phone: '+55 21 90011-4646',
    city: 'Rio de Janeiro',
    state: 'RJ',
    desiredRole: 'Infrastructure Engineer',
    areaOfExpertise: 'On-Prem Infrastructure',
    yearsOfExperience: 10,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 12.000 – R$ 15.000',
    availabilityDate: '2026-11-01',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Networks',
    institution: 'UERJ',
    certifications: ['VMware VCP', 'CCNA', 'Red Hat RHCSA'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Infrastructure engineer managing VMware virtualisation and hybrid cloud environments for media companies.',
    keyTechnicalSkills: ['VMware vSphere', 'Linux', 'Storage (NetApp)', 'Networking', 'Backup & DR'],
    softwareTools: ['vCenter', 'Veeam', 'SolarWinds', 'Ansible'],
    mainAchievements: 'Designed DR strategy achieving RTO of 2 hours for mission-critical broadcast systems.',
    submittedAt: '2026-05-06T11:00:00Z',
    lastUpdatedAt: '2026-05-06T11:00:00Z',
    status: 'Rejected',
  },
  {
    id: '47',
    fullName: 'Clara Esteves',
    email: 'clara.esteves@email.com',
    phone: '+55 11 99900-4747',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/claraesteves',
    portfolio: 'claraesteves.design',
    desiredRole: 'Brand Designer',
    areaOfExpertise: 'Brand & Identity',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 7.000 – R$ 9.000',
    availabilityDate: '2026-07-20',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Graphic Design',
    institution: 'PUC-SP',
    certifications: ['Adobe Certified Expert'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Brand designer creating visual identities and brand guidelines for startups and scale-ups across LatAm.',
    keyTechnicalSkills: ['Brand Strategy', 'Logo Design', 'Typography', 'Illustration', 'Motion'],
    softwareTools: ['Illustrator', 'Photoshop', 'After Effects', 'Figma'],
    mainAchievements: 'Created brand identity adopted by a Series B startup that raised $12M shortly after rebrand.',
    submittedAt: '2026-05-05T13:00:00Z',
    lastUpdatedAt: '2026-05-05T13:00:00Z',
    status: 'New',
  },
  {
    id: '48',
    fullName: 'André Machado',
    email: 'andre.machado@email.com',
    phone: '+55 71 98899-4848',
    city: 'Salvador',
    state: 'BA',
    desiredRole: 'ERP Consultant',
    areaOfExpertise: 'ERP Implementation',
    yearsOfExperience: 9,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 13.000 – R$ 16.000',
    availabilityDate: '2026-10-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "MBA",
    courseMajor: 'Business Management',
    institution: 'FGV',
    certifications: ['SAP S/4HANA Finance', 'SAP Business One Consultant'],
    languages: ['Portuguese', 'English', 'Spanish'],
    professionalSummary: 'SAP ERP consultant delivering Finance and Supply Chain modules for mid-market and enterprise clients.',
    keyTechnicalSkills: ['SAP S/4HANA', 'SAP Finance', 'Supply Chain', 'Change Management'],
    softwareTools: ['SAP', 'MS Project', 'Visio'],
    mainAchievements: 'Delivered SAP go-live for $500M distributor 3 weeks ahead of schedule.',
    resumeFileName: 'andre-machado-resume.pdf',
    submittedAt: '2026-05-04T10:00:00Z',
    lastUpdatedAt: '2026-05-04T10:00:00Z',
    status: 'Under Review',
  },
  {
    id: '49',
    fullName: 'Letícia Pires',
    email: 'leticia.pires@email.com',
    phone: '+55 81 97788-4949',
    city: 'Recife',
    state: 'PE',
    desiredRole: 'Customer Experience Analyst',
    areaOfExpertise: 'CX / Customer Journey',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 5.500 – R$ 7.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Psychology',
    institution: 'UFPE',
    certifications: ['CX Professional (CXPA)', 'NPS Certification'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'CX analyst mapping and improving customer journeys for telecoms and utilities companies.',
    keyTechnicalSkills: ['Journey Mapping', 'NPS', 'Voice of Customer', 'Persona Design', 'CRM'],
    softwareTools: ['Medallia', 'Salesforce', 'Miro', 'Tableau'],
    mainAchievements: 'Increased NPS from 24 to 58 in 12 months through CX transformation programme.',
    submittedAt: '2026-05-03T09:00:00Z',
    lastUpdatedAt: '2026-05-03T09:00:00Z',
    status: 'Approved',
  },
  {
    id: '50',
    fullName: 'Fábio Queiroz',
    email: 'fabio.queiroz@email.com',
    phone: '+55 85 96677-5050',
    city: 'Fortaleza',
    state: 'CE',
    linkedIn: 'linkedin.com/in/fabioqueiroz',
    desiredRole: 'Software Engineering Manager',
    areaOfExpertise: 'Engineering Leadership',
    yearsOfExperience: 12,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 22.000 – R$ 28.000',
    availabilityDate: '2026-12-01',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Master's",
    courseMajor: 'Software Engineering',
    institution: 'UFC',
    certifications: ['AWS Solutions Architect Professional', 'CKA'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Engineering manager leading teams of 15+ engineers delivering cloud-native products in the fintech space.',
    keyTechnicalSkills: ['Team Leadership', 'Technical Strategy', 'System Design', 'Hiring', 'OKRs'],
    softwareTools: ['Jira', 'Confluence', 'GitHub', 'Datadog', 'PagerDuty'],
    mainAchievements: 'Scaled engineering team from 5 to 22 while maintaining <2% voluntary attrition over 2 years.',
    resumeFileName: 'fabio-queiroz-resume.pdf',
    submittedAt: '2026-05-02T08:00:00Z',
    lastUpdatedAt: '2026-05-02T08:00:00Z',
    status: 'New',
  },
]
