import { Candidate } from './types'

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    fullName: 'Ana Oliveira',
    email: 'ana.oliveira@email.com',
    phone: '+55 11 99999-1111',
    city: 'São Paulo',
    state: 'SP',
    linkedIn: 'linkedin.com/in/anaoliveira',
    portfolio: 'anaoliveira.dev',
    desiredRole: 'Frontend Developer',
    areaOfExpertise: 'Web Development',
    yearsOfExperience: 5,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 8.000 – R$ 10.000',
    availabilityDate: '2026-07-15',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Computer Science',
    institution: 'USP',
    certifications: ['AWS Cloud Practitioner'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Senior frontend developer with 5 years building React applications for fintech companies.',
    keyTechnicalSkills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    softwareTools: ['VS Code', 'Figma', 'GitHub'],
    mainAchievements: 'Led migration of legacy jQuery app to React, reducing load time by 40%.',
    resumeFileName: 'ana-oliveira-resume.pdf',
    submittedAt: '2026-06-18T10:23:00Z',
    lastUpdatedAt: '2026-06-18T10:23:00Z',
    status: 'Under Review',
    internalNotes: 'Strong portfolio. Schedule technical interview.',
  },
  {
    id: '2',
    fullName: 'Carlos Mendes',
    email: 'carlos.mendes@email.com',
    phone: '+55 21 98888-2222',
    city: 'Rio de Janeiro',
    state: 'RJ',
    linkedIn: 'linkedin.com/in/carlosmendes',
    desiredRole: 'Backend Developer',
    areaOfExpertise: 'API Development',
    yearsOfExperience: 3,
    currentEmploymentStatus: 'Freelancer',
    salaryExpectation: 'R$ 6.000 – R$ 8.000',
    availabilityDate: '2026-08-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Bachelor's",
    courseMajor: 'Systems Analysis',
    institution: 'UERJ',
    certifications: [],
    languages: ['Portuguese', 'Spanish'],
    professionalSummary: 'Backend developer specialising in Node.js REST APIs and PostgreSQL.',
    keyTechnicalSkills: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    softwareTools: ['VS Code', 'Postman', 'GitHub'],
    mainAchievements: 'Built a payment gateway integration handling 50k transactions/day.',
    resumeFileName: 'carlos-mendes-resume.pdf',
    submittedAt: '2026-06-19T14:05:00Z',
    lastUpdatedAt: '2026-06-20T09:00:00Z',
    status: 'New',
  },
  {
    id: '3',
    fullName: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    phone: '+55 31 97777-3333',
    city: 'Belo Horizonte',
    state: 'MG',
    linkedIn: 'linkedin.com/in/fernandalima',
    desiredRole: 'UX Designer',
    areaOfExpertise: 'Product Design',
    yearsOfExperience: 7,
    currentEmploymentStatus: 'Employed',
    salaryExpectation: 'R$ 9.000 – R$ 12.000',
    availabilityDate: '2026-09-01',
    preferredWorkModel: 'Remote',
    degreeLevel: "Master's",
    courseMajor: 'Design',
    institution: 'UFMG',
    certifications: ['Google UX Design Certificate'],
    languages: ['Portuguese', 'English', 'French'],
    professionalSummary: 'UX designer with 7 years creating user-centred digital products across healthcare and retail.',
    keyTechnicalSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    softwareTools: ['Figma', 'Maze', 'Notion'],
    mainAchievements: 'Redesigned onboarding flow increasing activation rate by 28%.',
    resumeFileName: 'fernanda-lima-resume.pdf',
    submittedAt: '2026-06-20T08:30:00Z',
    lastUpdatedAt: '2026-06-21T11:15:00Z',
    status: 'Approved',
    internalNotes: 'Excellent fit. Offer letter in progress.',
  },
  {
    id: '4',
    fullName: 'Rafael Costa',
    email: 'rafael.costa@email.com',
    phone: '+55 41 96666-4444',
    city: 'Curitiba',
    state: 'PR',
    desiredRole: 'DevOps Engineer',
    areaOfExpertise: 'Cloud Infrastructure',
    yearsOfExperience: 2,
    currentEmploymentStatus: 'Student',
    salaryExpectation: 'R$ 4.000 – R$ 5.500',
    availabilityDate: '2026-07-01',
    preferredWorkModel: 'Onsite',
    degreeLevel: "Bachelor's",
    courseMajor: 'Information Technology',
    institution: 'UTFPR',
    certifications: ['AWS Solutions Architect Associate'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Junior DevOps engineer with hands-on experience in CI/CD pipelines and Kubernetes.',
    keyTechnicalSkills: ['Docker', 'Kubernetes', 'Terraform', 'AWS'],
    softwareTools: ['GitHub Actions', 'Grafana', 'Datadog'],
    mainAchievements: 'Implemented GitOps workflow reducing deployment time from 45 min to 8 min.',
    submittedAt: '2026-06-21T16:45:00Z',
    lastUpdatedAt: '2026-06-21T16:45:00Z',
    status: 'Rejected',
    internalNotes: 'Good potential but insufficient experience for current seniority requirement.',
  },
  {
    id: '5',
    fullName: 'Beatriz Santos',
    email: 'beatriz.santos@email.com',
    phone: '+55 51 95555-5555',
    city: 'Porto Alegre',
    state: 'RS',
    linkedIn: 'linkedin.com/in/beatrizsantos',
    desiredRole: 'Data Analyst',
    areaOfExpertise: 'Business Intelligence',
    yearsOfExperience: 4,
    currentEmploymentStatus: 'Unemployed',
    salaryExpectation: 'R$ 5.500 – R$ 7.000',
    availabilityDate: '2026-06-30',
    preferredWorkModel: 'Hybrid',
    degreeLevel: "Bachelor's",
    courseMajor: 'Statistics',
    institution: 'UFRGS',
    certifications: ['Google Data Analytics'],
    languages: ['Portuguese', 'English'],
    professionalSummary: 'Data analyst experienced in building BI dashboards and ETL pipelines for retail companies.',
    keyTechnicalSkills: ['Python', 'SQL', 'Power BI', 'dbt'],
    softwareTools: ['Power BI', 'BigQuery', 'Metabase'],
    mainAchievements: 'Built sales forecasting model that improved inventory accuracy by 22%.',
    resumeFileName: 'beatriz-santos-resume.pdf',
    submittedAt: '2026-06-22T09:00:00Z',
    lastUpdatedAt: '2026-06-22T09:00:00Z',
    status: 'New',
  },
]
